include: package:lint/analysis_options_package.yaml

# https://www.dartlang.org/guides/language/analysis-options
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

# Source of linter options:
# http://dart-lang.github.io/linter/lints/options/options.html
linter:
  rules:
    camel_case_types: true
    hash_and_equals: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    unrelated_type_equality_checks: true
    valid_regexps: true
    prefer_single_quotes: true
    public_member_api_docs: false
    avoid_escaping_inner_quotes: true
    avoid_catches_without_on_clauses: true
    avoid_js_rounded_ints: true
    avoid_returning_null: true
    avoid_returning_this: true
    close_sinks: true
    prefer_adjacent_string_concatenation: true
    no_adjacent_strings_in_list: true
    unawaited_futures: true
    prefer_final_locals: true
    prefer_final_fields: true
    # Good practice for public widget API. Otherwise less helpful in apps
    use_key_in_widget_constructors: false
